### ISSUE TITLE
Discussion - Sass

### ISSUE THREAD

**Issue by tdhartwick** [zurb/foundation-emails#10]
We've Sassified our workflow! You can now access all of the mighty powers that Sass offers, including mixins, functions, and variables! We're really looking forward to seeing how people use variables within the new Foundation for Emails. The idea is to update a variable within your `_settings.scss`, such as a primary color, and see your style cascade everywhere it needs to go! We're interested in a few things around this:  

1. Do we have the all the variables you expected?
2. How often do you think you'll use these Sass variables?
3. Did it work like you'd expect?

**Comment by gakimball** [comment]
This issue was moved to zurb/ink#161
