### ISSUE TITLE
template not preview properly in Higher resolution phone.

### ISSUE THREAD

**Issue by umesh25** [zurb/foundation-emails#102]
Here is the template link

http://developerinfotek.com/demo/extragroup/outlook.html

this is working on most of browser but it not showing properly in high resolution small width phone.
Mainly this issue in SAMSUNG EMAIL client. Model SAMSUNG GALAXY S3 and above version.

Red Mark in image is the issue. 
AS PER media query email Show Mobile View , but it show Desktop view.

What is solution for this issue.
![2014-07-30 16 03 36-1](https://cloud.githubusercontent.com/assets/2259238/3795620/9f54fbf6-1bbd-11e4-9547-7b4b8d24ac03.png)

**Comment by tdhartwick** [comment]
This should be addressed in v2. We're not supporting v1 currently, however we're more than happy to merge in a PR for v1.0.0. Thanks!
