### ISSUE TITLE
First ROW of CONTAINER if full width IMG issuee

### ISSUE THREAD

**Issue by hairorh** [zurb/foundation-emails#103]
In Outlook 2003 there is an issue when using a header image with nothing above. To clean the issue up I just delete the full width row of the top and the text tags of the second row in the sidebar-hero template.
https://www.emailonacid.com/app/acidtest/viewresult/1aglkhzqTqsIbA5Bvo40tXTGEGLfto0QcYgRhO9GD2ntN

**Comment by tdhartwick** [comment]
This should be addressed in v2. We're no longer supporting v1, but we're more than happy to merge a PR into the v1.0.0 branch. Thanks!
