### ISSUE TITLE
Tables within tables and child selectors

### ISSUE THREAD

**Issue by jdelight** [zurb/foundation-emails#109]
Is there a reason why the styles applied to  table cells cannot be specific to the only the cells needed for the grid framework?

I've run into issues when nesting tables within a grid structure which I've avoided by using child selectors:

```
table.columns > td,
table.column > td {
  padding: 0px 0px 10px;
}
```
instead of:
```
table.columns td,
table.column td {
  padding: 0px 0px 10px;
}
```

Similarly with the responsive styles, could you use:
```
  table[class="body"] table.columns > td,
  table[class="body"] table.column  > td {
    width: 100% !important;
  }
```

instead of:
```
  table[class="body"] table.columns td,
  table[class="body"] table.column td {
    width: 100% !important;
  }
```

Would be interested to hear you thoughts on this - and thanks for a fantastic framework.
James

**Comment by mattdbridges** [comment]
I just started using this framework today and it's absolutely wonderful...

Except for this part. I too would like to keep control of `table` elements that are not being used for layout.

**Comment by tdhartwick** [comment]
We're no longer supporting v1, however we've restructured the sass and layout a bit that may have fixed this issue. We've updated the specificity by including a large and small grid, so this should address this issue. Let us know if this is still an issue. 

We're also merging PRs into the v1.0.0 if you'd like to still contribute to the older version. 

Thanks!
