### ISSUE TITLE
Since 1.0.2, only the labels of buttons are clickable

### ISSUE THREAD

**Issue by stigmm** [zurb/foundation-emails#11]
Sorry. This is a follow up to #4.

I know there aren't (m)any great ways to code buttons for email, but making the actual button shape non-clickable is a pretty big usability flaw.

Leaving this here in case you find an other option.

**Comment by rafibomb** [comment]
Resolved in v2.0 using padding/border hybrid method
number 4 here: https://litmus.com/blog/a-guide-to-bulletproof-buttons-in-email-design
