### ISSUE TITLE
Discussion - Panini

### ISSUE THREAD

**Issue by tdhartwick** [zurb/foundation-emails#11]
In this version of Foundation for Emails we've included [our flat file generator, Panini](https://github.com/zurb/panini). This let's us keep consistent head and footers so that we can just include the body styles and content, making it easy to whip out stylistically similar emails in a synch. We want to know:

1. does Panini make sense in the Foundation for Emails?
2. Would you use Panini in your email projects?
3. Are you currently using a static site generator?
4. Are there features that you'd need to make Panini more useful for Email creation?

**Comment by gakimball** [comment]
This issue was moved to zurb/ink#162
