### ISSUE TITLE
Inliner breaks CSS

### ISSUE THREAD

**Issue by webberig** [zurb/foundation-emails#115]
Hi,

I'm seeing some weird behavior with the inliner. We're trying to override default ink styles with our own CSS. For some reason, the inliner removes our :hover CSS while keeping the original.

This is an example less file:
```
// Include ink
@import (less) "ink/css/ink.css";

// Green button
table.button.green td {
    background: @green;
    border-color: @green;
}
table.button.green:hover td,
table.button.green:visited td,
table.button.green:active td {
  background: @green !important;
}
```

The resulting CSS is included inline in the HTML and works as intended: the .button.green:hover styles override the default .button:hover style.

But after using the inliner (zurb.com/ink/inliner.php), our style (table.button.green:hover td) is removed while the default style (table.button:hover td) is kept.

The same thing happens if we drop the extra .green class: our css is removed, the default css stays...

You can find an example HTML file here:
http://pastebin.com/zkacjdrZ

Can anyone explain why and how we can avoid this behavior ?

**Comment by eudennis** [comment]
I'm with the same problems with CSS after passing code through inliner.

**Comment by tdhartwick** [comment]
This should be addressed in our updated inliner. Let us know if this problem still exists!
