### ISSUE TITLE
Test template not working responsively on Edge, Firefox and IE (works fine in Chrome)

### ISSUE THREAD

**Issue by bago** [zurb/foundation-emails#12]
When I test the bundled template using "npm test" I can see it correctly react to window-width changes only on Chrome while it breaks on Firefox, IE11, Edge 13 (windows 10).
![edge-13-foundemail2](https://cloud.githubusercontent.com/assets/173498/11903978/5dd1a0c2-a5bd-11e5-9fe2-fbf8d667379d.png)

I guess the issue is related to some CSS applying a ```display: block !important``` to ```<table>``` tags and Chrome not supporting altering the display on ```table``` (and other table related) tags.

Of course this doesn't seem an issue with foundation for emails itself, but maybe the default css.

**Comment by gakimball** [comment]
This issue was moved to zurb/ink#163
