### ISSUE TITLE
Expander cell has 1px width if non-breaking space is added

### ISSUE THREAD

**Issue by katart** [zurb/foundation-emails#123]
I've noticed that some Email Marketing software will add a `&nbsp;` string within any empty cell. This will make the expander cell appear with a 1px width. I tried adding `font-size: 0px !important;` and `line-height: 0 !important;` but that didn't help. The only thing that worked for me was to hide the expander cell above 600px and add `display:block` within the media query.

Is there a reason NOT to hide the expander cell above 600px width and only show it for mobile? Based on the Docs, it seems as if the expander cell is only for mobile devices.

**Comment by tdhartwick** [comment]
The expander is especially helpful for the nasty outlooks to ensure that cells expand to their correct size if their content is smaller. We've reworked the expander class in v2, however we're not supporting v1 anymore. We're more than happy to merge a PR on our v1.0.0 branch. Let us know if this is still a problem for v2. Thanks!
