### ISSUE TITLE
Change Doctype to XHTML Transitional

### ISSUE THREAD

**Issue by steadystatic** [zurb/foundation-emails#128]
I was trying to use Ink templates with W3C's HTML direct input validator or tidy on my Mac and found it painful.

Is there a reason why Ink doesn't just use XHTML Transitional? It seems to get around a lot of the errors. Beyond that, can we add type="text/css" to the style tags as well? 

I've done this on my templates and I know immediately when my funky long emails have one TD too many, etc.

Many thanks the Ink community and - I have loved getting started with it!

**Comment by elidickinson** [comment]
I can't speak for the Ink, but the goal is "works in email clients" not "passes validation." Many email clients have buggy/incomplete HTML parsing.

Transitional may work instead of Strict, but I'd definitely want to run a full suite of client tests first

**Comment by steadystatic** [comment]
Thanks for the response - I do see the value in being more focused on working in more clients. I am curious to help out and if there's some client tests I could run I'd be happy to volunteer!

I was half expecting there might be a good reason for the project with the strict doctype. I know many clients just strip doctype anyway so really this is more of a value to development and feedback before inlining. 

But I do see the value after working all week on some fresh email templates :)

**Comment by tomleo** [comment]
I think it should change to `Transitional`, I haven't found any indication that `Strict` helps with the goal of "works in email clients" vs. `Transitional`

**Comment by freemagee** [comment]
The responsive email design done over here:

http://webdesign.tutsplus.com/tutorials/creating-a-future-proof-responsive-email-without-media-queries--cms-23919

Their logic:

*!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" is the DOCTYPE I like best—I find it yields the fewest quirks.*

**Comment by tdhartwick** [comment]
Apologies for the delayed response. Is this still something that could be applied to v2? We're not currently supporting v1 anymore, however this looks like it could help.

**Comment by rafibomb** [comment]
Since we're on 2.1 now, this can be changed there. We'll close this here and apply the change for 2.2 coming soon. Thanks!

**Comment by florianbouvot** [comment]
@rafibomb Foundation for Emails Docs use strict ([CSS doc](http://foundation.zurb.com/emails/docs/css-guide.html#boilerplate), [Sass doc](http://foundation.zurb.com/emails/docs/sass-guide.html#boilerplate)) and [foundation-emails-template](https://github.com/zurb/foundation-emails-template/blob/master/src/layouts/default.html) use transitional.

Docs need an update?!
