### ISSUE TITLE
font-awesome

### ISSUE THREAD

**Issue by vasder** [zurb/foundation-emails#129]
Hi, 
Can we use font-awesome with responsive email design, my in scope email services are gmail, yahoo, aol, outlook.com. Please davice

**Comment by arabyalhomsi** [comment]
No you can't, convert icons to images in photoshop, after that you can include them in your email like any image.

**Comment by tdhartwick** [comment]
Looks like this has been addressed. Thanks for responding @arabyalhomsi!
