### ISSUE TITLE
Discussion  - Others

### ISSUE THREAD

**Issue by alfatreze** [zurb/foundation-emails#13]
I have a few doubts about the basic framework setup, regarding the GCC requirement.
I'm quite ok with installing but:
- What exactly is it used for?
- and what packages are actually required?
As there is a fair amount of them to choose from on MinGW.

**Comment by gakimball** [comment]
To close the loop on this:

- The GCC is required so Node can compile native modules. We use Libsass, a Sass compiler written in C, to compile Sass.
- Node versions as old as 0.12 should work with all of the Foundation templates. I use Node 5.3 and our current build systems are working fine.
- The [final template](https://github.com/zurb/foundation-sites-template) that developers will be using is finished, so all future testing should be done there.

If you run into any more issues, let us know. :)
