### ISSUE TITLE
Ink Standard Template not Responsive on iPhone 6 Plus

### ISSUE THREAD

**Issue by mkuczera** [zurb/foundation-emails#138]
Hello,

i currently got a problem with the iphone 6 plus. Inside Litmus all Tests are perfect, iPhone 6 and 6 Plus are displaying everything fine. But on the device the responsive behaviour is deactivated. Tried it with the Ink Standard Sidebar Template (http://zurb.com/ink/templates.php) but got the same issue. Is there any workaround?

Greetings

Michael

**Comment by abosio** [comment]
Is this because the effective width of the iPhone 6 and 6 Plus is 667 and 736, which is above the breakpoint for Ink's mobile size? (Not sure about Litmus results.)

**Comment by rafibomb** [comment]
Not able to replicate this on my iphone 6. We'll have to find a 6+ to test with and get back to you.

**Comment by tdhartwick** [comment]
Thanks for pointing this out, however, I'm having trouble replicating this on my device as well. Going to close this one down. We've updated the template to file issues here: https://github.com/zurb/foundation-emails/issues/new?title=%5BFoundation%20for%20Emails%5D%20ISSUE%20NAME%20HERE

Going to close this down until we can replicate it. Thanks!
