### ISSUE TITLE
Inlining should not place !important within bgcolor=''

### ISSUE THREAD

**Issue by unr** [zurb/foundation-emails#141]
Simple example, add `table.button td { background: red!important; }` and run the inliner.

---

## Problem Output
`<td class="button" style="background: red!important;" bgcolor="red !important">`

---

## Expected Output
`<td class="button" style="background: red!important;" bgcolor="red">`

---

By including the `!important` within the bgcolor, several email clients have issues. This should never happen. Only place the !important on the style tag.

**Comment by elidickinson** [comment]
Which inliner are you using? I've been working with https://github.com/peterbe/premailer with mostly good results

**Comment by unr** [comment]
Using the Ink Inliner, http://zurb.com/ink/inliner.php

**Comment by rafibomb** [comment]
Testing this out on the new version of Foundation for Emails 2 and the new web inliner http://foundation.zurb.com/emails/inliner-v2.html

Seems to not be happening anymore. We'll close this issue - open a new one if you see other inliner issues on the new version.
