### ISSUE TITLE
Hiding content in GMail and Outlook not working with Zurb Ink 1 implementation

### ISSUE THREAD

**Issue by crmpicco** [zurb/foundation-emails#145]
I am experiencing an issue using the Desktop/Mobile show/hide functionality with Zurb Ink email framework. When I use the CSS below it works correctly in GMail, where the mobile content is hidden and only desktop is shown, but not in Outlook. However, with the default Ink CSS (where there is no `!important` flag on the `display: none`) it works in Outlook but not in GMail. I am using Outlook 2010.

I have taken some inspiration from this Gist (https://gist.github.com/Riveascore/10549334) and i'm using this CSS:
```
div.gmail .show-for-small,
div.gmail .hide-for-desktop {
    display : none !important;
    mso-hide: all !important;
}
```
This is my email markup:
```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
    <html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta name="viewport" content="width=device-width"/>
        <style type="text/css">
            <!-- my inline styles in here -->
        </style>
    </head>
    <body>
    <!--[if !mso]><!-->
    <div class="gmail">
    <!--<![endif]-->
    <table class="body">...</table>
    <!--[if !mso]><!-->
    </div>
    <!--<![endif]-->
    </body>
```
What am I missing?

**Comment by akeilox** [comment]
Im new to Ink and reading through the documentation, so not in a place to comment in full knowledge.

But isnt the 
<pre>
  
</pre>

is the Outlook selector, if its not outlook then it wont render those?

**Comment by crmpicco** [comment]
Yes, so the intention is to create the div with a class of Gmail for non-Outlook readers. So I'm in the situation where this works for Gmail, but breaks Outlook - and I don't understand why?

**Comment by akeilox** [comment]
If Im following correctly,
  
    <div class="gmail">
    
    <table class="body">...</table>
    
    </div>
    

So outlook, by right, should ignore the opening and closing divs and only see
    <table class="body">...</table>

and this is not happening?

**Comment by crmpicco** [comment]
Well, the issue isn't specific to those MSO tags (I think). I'm using the hide-for-desktop and show-for-mobile classes in my HTML email templates and I'm unable to get them working on both Gmail and Outlook. There seems little in the way of documentation from Zurb about this, other than a Tweet from 2014 saying it may be fixed in Ink 2. Although maybe I've just not found the documentation yet - but I'm at a bit of a loss with this one...

**Comment by akeilox** [comment]
i think this might help greatly, it might be an outlook version issue as one can use if statements like "if mso 12" to target specific versions of outlook.

Nevertheless I find this article a very good read;
https://scotch.io/tutorials/building-responsive-email-templates-with-ink

**Comment by crmpicco** [comment]
Yes, thank you however i've tried all that sort of stuff. The problem that the posts I have come across don't seem to resolve is how to show the correct content for mobile desktop (with the Zurb `hide-for-desktop` classes on multiple clients.

Based on that Scotch.io post I dropped this into the `<head>` tag. But it doesn't get picked up on GMail. I assumed this read as "IF NOT MS OUTLOOK THEN DO THIS".

```
        <!--[if !mso]><!-- -->
        <style type="text/css">
            .show-for-small, .hide-for-desktop {
                display : none !important;
                mso-hide: all !important;
            }
        </style>
        <!--<![endif]-->
```

**Comment by akeilox** [comment]
Thats correct, mso stands for microsoft outlook, so it includes that only-if-not outlook as there is negate ! in front.

You can even go ahead and add version too;
like





instead of number using just mso detects all outlook (i presume)

**Comment by crmpicco** [comment]
Any idea why my CSS doesn't work as per https://github.com/zurb/ink/issues/145#issuecomment-142219150 ?

**Comment by akeilox** [comment]
I am not sure but it seems your exclusion is the one to look at;

i would try if !mso]  vs if mso]  - to exclude or not exclude outlook check.

**Comment by crmpicco** [comment]
@akeilox Everything I have read suggests doing `[if !mso]` - but this just doesn't work. I'm surprised the Ink project doesn't support the ability to show/hide on desktop/mobile with their built-in classes out the box.

**Comment by tdhartwick** [comment]
@crmpicco Apologies for the delayed response, this seems like an interesting issue. This may have been an issue with the v1 specificity. We're no longer supporting v1, but we're merging PRs into our v1.0.0 branch.

I'm curious if you've taken a look at this on v2? If so can you file a new issue for that for us to look into.

Thanks!
