### ISSUE TITLE
npm install ?

### ISSUE THREAD

**Issue by sgarbesi** [zurb/foundation-emails#148]
$ npm install Ink --save
npm ERR! Linux 3.13.0-55-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "Ink" "--save"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/Ink
npm ERR! 404 
npm ERR! 404 'Ink' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because
npm ERR! 404 
npm ERR! 404  1. name can no longer contain capital letters
npm ERR! 404 It was specified as a dependency of '...'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by tdhartwick** [comment]
We're currently using https://www.npmjs.com/package/foundation-emails

V2 takes care of most of the setup for you. Check it out here: http://foundation.zurb.com/emails/getting-started.html
