### ISSUE TITLE
The best approach to lay out 3 social media icons at the bottom center

### ISSUE THREAD

**Issue by akeilox** [zurb/foundation-emails#154]
Can anyone chip in on the best approach to lay out 3 social media icons, centered at the bottom of the email?

Its easy to center text but not sure how to go about centering three <img at the bottom (footer) of the email.

**Comment by tdhartwick** [comment]
You should be able to use `text-align: center` for the three images. We're more than happy to answer this in more detail on our forum here: http://foundation.zurb.com/forum

Thanks!
