### ISSUE TITLE
Windows Phone 10 Support

### ISSUE THREAD

**Issue by MartinAltEAS** [zurb/foundation-emails#155]
Our test according to Windows Phone 10 with INK showed up a broken view.
Seems to have completey wrong width for all major containers and images, too.

Short test with a real device and some additional test with windows phone emulator showed up the same results - see screenshots.

The E-Mail had been testes via "email on acid" and inlined by zurb inliner and looks good on most devices, including windows Phone 8.

See screenshots of Windows Phone 10:
![wp10_01](https://cloud.githubusercontent.com/assets/16914662/12607709/45a2dd3e-c4d7-11e5-841d-55fb4aedaaad.png)
![wp10_02](https://cloud.githubusercontent.com/assets/16914662/12607710/45ac206a-c4d7-11e5-8837-466edca6f7cf.png)

and screenshots of Windows Phone 8:
![wp8_01](https://cloud.githubusercontent.com/assets/16914662/12608290/8ee5b0da-c4db-11e5-99de-8ba1a5e9b038.png)
![wp8_02](https://cloud.githubusercontent.com/assets/16914662/12608291/8ee5b63e-c4db-11e5-837a-57482aacba5e.png)

Would be great to get support for this device, too.

**Comment by rafibomb** [comment]
We have one of these to test on for v2. Good thing you have one too. We'll be opening up a Release Candidate soon to test on and we can address any issues on Windows Phone 10

**Comment by rafibomb** [comment]
Have you used the new version of Foundation for emails with this device? Would love to know how it goes!

**Comment by rafibomb** [comment]
Havn't had any reports of this on the new version. Are you using Gmail, Outlook, or Yahoo on this device?

**Comment by rafibomb** [comment]
Tested about 6 templates on a Windows phone 10 with Outlook and Gmail. No issues! Please open a new issue with a code example if anything comes up with version 2.2+

**Comment by MartinAltEAS** [comment]
Hi Rafi,

thanks for the effort and the support of Windows Phone 10 for version 2.

Actually, we’re still including all the transactional emails from version 1 in our code.

The code is there y big overhead right now. Is it correct, that the migration process from v1 to v2 is about huge code changes or can we still use the code from version 1 as an base to get the css working from v2 in order to support windows phone 10?

Thanks for all your help!

Best,

Martin

Martin Alt
Frontendentwickler

easyautosale GmbH
Dingolfinger Straße 1-15
81673 München

tel: 089/444 56-3735
fax: 089/444 56-193735

Martin.Alt@easyautosale.commailto:Martin.Alt@easyautosale.com
www.easyautosale.com

Geschäftsführer: Christian Bubenheim, Stefan Lemper
Sitz der Gesellschaft: München
Handelsregister München: HRB 190898

Am 16.06.2016 um 22:25 schrieb Rafi <notifications@github.com<mailto:notifications@github.com>>:

Tested about 6 templates on a Windows phone 10 with Outlook and Gmail. No issues! Please open a new issue with a code example if anything comes up with version 2.2+
