### ISSUE TITLE
last class added with no blank space( )

### ISSUE THREAD

**Issue by klangwiedergabe** [zurb/foundation-emails#28]
The last class is added without any space if you add a custom class to your last td.

Example
in your last  td a.k.a. columns you want to call it: columns class="yolo"

But you get:
td class="yololast"

You can obviously make a manual space at the end your class and fix it, but I guess the instruction should be like "add a last class if it's your last columns" because "add a blank space if is your last columns" is much easier to miss. You can't really visualise what you got wrong.

Or

just make it happen automagically :)

**Comment by gakimball** [comment]
Fixed in the latest version of Inky.
