### ISSUE TITLE
npm test throws error for babel module

### ISSUE THREAD

**Issue by krypsin** [zurb/foundation-emails#30]
Am on Linux Mint 17.2
node -v: v0.12.7
npm -v: 2.11.3

When I run `npm test` in my foundation for emails folder, I get the following errors:
[15:32:13] Requiring external module babel-core/register
/home/leehanbury/repos/foundation-emails/testing/gulpfile.babel.js:89
_gulp2.default.task('build', _gulp2.default.series.apply(_gulp2.default, build
                                                  ^
TypeError: Cannot read property 'apply' of undefined
    at Object.<anonymous> (gulpfile.babel.js:70:3)
    at Module._compile (module.js:460:26)
    at loader (/home/leehanbury/repos/foundation-emails/node_modules/babel-core/node_modules/babel-register/lib/node.js:130:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/leehanbury/repos/foundation-emails/node_modules/babel-core/node_modules/babel-register/lib/node.js:140:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Liftoff.handleArguments (/home/leehanbury/repos/foundation-emails/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/home/leehanbury/repos/foundation-emails/node_modules/gulp/node_modules/liftoff/index.js:192:16)

npm ERR! Linux 3.16.0-38-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! foundation-emails-template@0.0.1 start: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the foundation-emails-template@0.0.1 start script 'gulp'.
npm ERR! This is most likely a problem with the foundation-emails-template package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get their info via:
npm ERR!     npm owner ls foundation-emails-template
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/leehanbury/repos/foundation-emails/testing/npm-debug.log
npm ERR! Test failed.  See above for more details.

I can't see for the life of me why this isn't working. Any ideas?

**Comment by gakimball** [comment]
We put out an initial [release candidate](https://github.com/zurb/foundation-emails/releases/tag/v2.0.0-rc.1) today for Foundation for Emails 2, and along with that [a dedicated template repo](https://github.com/zurb/foundation-emails-template) for testing. All future testing will happen on that template, instead of the one built into this repo.

If you encounter any more issues with the final template, could you let us know here? Thanks. :)

**Comment by krypsin** [comment]
Sorry if I'm missing something here, but there isn't an issues page on the final template repo.

Anyway, I still have a similar issue with the new template repo :(

Everything looks a lot cleaner now, and works to some degree, however I still get:
`[15:48:57] Failed to load external module babel-register`
When I run `foundation watch`

Same npm and node versions as OP

What can we try next?

**Comment by gakimball** [comment]
[See the discussion here on this error.](https://github.com/zurb/ink/issues/178#issuecomment-187412382)

We don't have open issue trackers for the templates—instead, we just have folks open issues on the framework itself. Helps us keep things more consolidated.
