### ISSUE TITLE
Provide the CSS as LESS with variables

### ISSUE THREAD

**Issue by PhilippSchreiber** [zurb/foundation-emails#31]
Hey there,
I have the problem, that my newsletter needs to have a 20px padding on text-pad elements. If I overwrite the padding there are artefacts on the complete table width when using a two col layout. So I tried to change all 10px paddings to 20px which did not work too.
What about providing the CSS file as a LESS files with just a few variables where one can set margins, widths, etc. and the rest of the stylesheet gets calculated?
Cheers
Philipp

**Comment by sagikazarmark** [comment]
This is really old know. When can we expect a SCSS version?

**Comment by WillsB3** [comment]
+1 for SCSS verison. I need to change the grid size slightly (to make it around 460px instead of 580px). We shouldn't need to calculate all the column widths manually for this.

**Comment by ierpe** [comment]
+1

**Comment by heeton** [comment]
+1

**Comment by elidickinson** [comment]
I've been using this "unofficial" SASS version of Ink that is *really* well done. https://github.com/faustgertz/sassy-ink

It's very well laid out with separate files, functions and variables. And it compiles to an essentially byte-for-byte identical ink.css

**Comment by LucasKA** [comment]
+1 for an Official Sass version, I ported things over to Sass too, but not sure I'm breaking anything in the compilation.

**Comment by elidickinson** [comment]
I agree Sass should just be in the official repo, but @LucasKA, you should take a closer look at sassy-ink they put a lot of effort into setting it up to build a css file that is provably identical to the official ink.css

**Comment by LucasKA** [comment]
@elidickinson I'll check it out, I just did a Diff on Ink's CSS with my compiled output and it's verbatim other than the variables I set in my own Config.

I will check out Sassy-Ink, but I combined the Ink framework with Grunt-Email-Workflow for building/previewing. Not sure how to maintain it all. lol.

https://github.com/leemunroe/grunt-email-workflow

**Comment by elidickinson** [comment]
@LucasKA That looks nice. The test/build process is the only missing piece for us so this might finally be the thing that gets me to really learn grunt

**Comment by LucasKA** [comment]
@elidickinson No real need to learn Grunt per se, the tool that Lee Monroe built is pretty ready to go, I just converted Ink's Monolithic CSS files into Scss partials, and the tool builds it and Inlines it.

Maybe I could do Sassy-Ink as a submodule of the build tool, haha. Ned more :watch:

**Comment by LucasKA** [comment]
@elidickinson Ok, this has been on my radar for a while, so fuck it, I just did it real quick. I combined this project and Sassy-Ink

https://github.com/LucasKA/mail-builder

These two projects were MADE to go together, but I'd love some feedback and or questions and stuff.

**Comment by gakimball** [comment]
Hey friends, to close the loop on this, Foundation for Emails 2.0 is fully Sass powered. You can check out the development branch for it [here](https://github.com/zurb/foundation-emails/tree/v2.0).

We'll have a more formal announcement later in the week on the ZURB blog with a rundown of what's new from version 1.0 to 2.0.
