### ISSUE TITLE
Changes not taking effect in production

### ISSUE THREAD

**Issue by rafibomb** [zurb/foundation-emails#40]
Running `npm run production` starts the server and loads the page in browser. Changing CSS does not show until command is run again.

**Comment by gakimball** [comment]
Confirmed to still be happening in the [template repo](https://github.com/zurb/foundation-emails-template).

**Comment by gakimball** [comment]
This is only an issue if we need to be able to live develop with the inliner. Which is to say, you can keep the server running and it inlines every time, versus you running the inlining process once.

@tdhartwick @rafibomb Do we need live watching functionality with the inlining process? With the other frameworks, when you build for production, it's a one-time build.

**Comment by gakimball** [comment]
This issue was moved to zurb/ink#174
