### ISSUE TITLE
min-width conflicting with text-pad classes (padding in general)

### ISSUE THREAD

**Issue by bradcliffe** [zurb/foundation-emails#51]
So it would seem that applying `.center` to  `<td class="text-pad">` and wrapping its content in a `<center>` tag extends the width of the container by the width of the padding. Is this expected, or is there a proper way to circumvent this?

For the time being, I'm just dropping the `.center` class and `<center>` and applying `.center` to the content itself (it's a headline on its own row). I tested in Litmus and it works fine. I would possibly just advise either a fix (if there is one) or an update to the docs on how center might affect the widths where padding/margins is being applied.

**Comment by tdhartwick** [comment]
We no longer are using the `.text-pad` classes in v2. 

We are also no longer supporting ink v1. We're happy to take a pr on the v1.0.0 branch though!
