### ISSUE TITLE
Extra spacing on both left and right side around the image

### ISSUE THREAD

**Issue by casper1000** [zurb/foundation-emails#53]
There're about 2px extra spacing on both left and right sides around the image. This issue appears in Outlook 2001-2003, AOL (IE & Firefox). See screenshot below or attached. At first, i thought i accidentally changed the code causing that problem. But I took Zurb's template and ran a test in Litmus, got the same issue. I couldn't use the framework unless it's fixed. Other than that, I love it.

![screen shot](https://f.cloud.github.com/assets/6390449/1901329/62dce4ea-7c62-11e3-893c-8270dcf5d80e.jpg)
![screen shot 2014-01-13 at 9 48 19 am](https://f.cloud.github.com/assets/6390449/1901331/68ba40c4-7c62-11e3-8c31-f1aacd5d28c3.jpg)
![screen shot 2014-01-13 at 9 58 58 am](https://f.cloud.github.com/assets/6390449/1901409/b33c20f8-7c63-11e3-9cb1-988168ff9f37.png)

**Comment by tdhartwick** [comment]
We're no longer supporting v1. We've also updated our inliner. Let us know if this is still an issue!
