### ISSUE TITLE
Center block-grid elements on smaller widths

### ISSUE THREAD

**Issue by kevnk** [zurb/foundation-emails#55]
By default, the block-grids are not centered when the viewport is skinnier:  

![ink responsive email documentation 2014-01-30 15-20-49](https://f.cloud.github.com/assets/1181420/2045150/655eab00-89f4-11e3-86f0-3a661939ded7.jpg)

You can fix this by adding a `text-align:center` to the parent `tr` like so:

	<table class="block-grid two-up">
		<tr style="text-align: center;">
			<td>
				
			</td><td>
				
			</td>
		</tr>
	</table>

Then it will look like this:  

![ink responsive email documentation 2014-01-30 15-31-34](https://f.cloud.github.com/assets/1181420/2045247/e6bf3f38-89f5-11e3-92ef-ca6bda2b73fc.jpg)

I think this is likely the more desired effect for mobile when working with block-grid and may be worth considering adding it to ink's default styles.

**Comment by jer0dh** [comment]
Thank you!  This helped me.  I do want them centered

**Comment by tdhartwick** [comment]
It looks like this is pretty easy to achieve with one css rule. By default we still want block-grid elements to float left to maintain consistency with f4s. Let us know if there's a better way we can improve this!
