### ISSUE TITLE
Body Class

### ISSUE THREAD

**Issue by dewedrop** [zurb/foundation-emails#68]
I have been testing an email in outlook.com on a desktop. I had noticed other emails were responsive, but mine was not, when I reduced the browser size.

On inspecting the code, I discovered outlook.com prefixes the all the classes with ecx in the style sheet. However, it specifically does not prefix the table.body class in the main html.

I adapted all the body classes to "ibody" and this works on the desktop (but unfortunately not the mobile version).

Whilst it is not a full solution to outlook.com - I wondered whether changing the table.body class has any implications elsewhere.? If I might as well adjust the class name.

Thanks

**Comment by rafibomb** [comment]
Looking into this for 2.0. If there is a breaking change, we can do it there.

**Comment by rafibomb** [comment]
This is in v2.0!
