### ISSUE TITLE
Clicking inside an Ink email in Outlook 2013 causes changing margins

### ISSUE THREAD

**Issue by bjxrn** [zurb/foundation-emails#70]
In Outlook 2013, when you click next to a piece of content in an Ink email the content below it gets bumped down. At least in some situations. The extra margin gets removed when you click inside the header or on the content below. 

See screens below of the latest Zurb Ink newsletter, and of the blank Ink boilerplate.

![zurb-outlook2013-1](https://cloud.githubusercontent.com/assets/777026/2538337/72a03754-b5bc-11e3-92fd-f86cfd477b35.gif)

![zurb-outlook2013-2](https://cloud.githubusercontent.com/assets/777026/2538336/72a00df6-b5bc-11e3-8847-b6ccb8baa303.gif)

**Comment by tdhartwick** [comment]
We're no longer supporting ink v1. However, we're interested in knowing if this is still an issue. Please let us know how we can replicate this in v2. We're also still accepting PR's on the v1.0.0 branch.
Thanks!
