### ISSUE TITLE
Center content on smaller widths

### ISSUE THREAD

**Issue by brettdewoody** [zurb/foundation-emails#71]
Centering content on larger devices is easy with the `.center` and `center` method. But on smaller widths the centering is lost.

Is there a way keep the centering on smaller widths?

**Comment by jondcallahan** [comment]
:+1: thanks @brettdewoody !

**Comment by tdhartwick** [comment]
Looks like this was confirmed that it's working. Let us know if you're running into this for v2 as well! Thanks!
