### ISSUE TITLE
Mobile/Fluid mode content width issues

### ISSUE THREAD

**Issue by ljacobs-sml** [zurb/foundation-emails#72]
My paragraphs/cells were shrinking to the width of the content in many cases in mobile/fluid mode. This was causing me to lose my centered and right aligned text in blocks.

Have yet to test it on EOA but I resolved it with the following change..

  table[class="body"] .row {
    width: 100% !important;
    display: block !important;
  }

to 

  table[class="body"] .row {
    width: 100% !important;
    display: table !important;
  }

**Comment by nicolas-t** [comment]
awesome !

thanks !

**Comment by tdhartwick** [comment]
We're no longer supporting Ink v, but it looks like this issue was addressed. If this is still an issue we're more than happy to accept a PR on the v1.0.0 branch!

Thanks!
