### ISSUE TITLE
center doesn't work for h1, h2, p, etc. tags

### ISSUE THREAD

**Issue by ayhoung** [zurb/foundation-emails#73]
![new issue zurb_ink](https://cloud.githubusercontent.com/assets/308375/2620593/3157af76-bc41-11e3-90b6-766f988d674d.jpg)

**Comment by tdhartwick** [comment]
This should be resolved in v2! We're no longer supporting Ink v1. If this is still an issue we're more than happy to accept a PR on the v1.0.0 branch!
