### ISSUE TITLE
IE10/11 images scaling not working

### ISSUE THREAD

**Issue by PieterBosNr1** [zurb/foundation-emails#81]
The basic templates image resizing do not work in IE10/11. that makes online viewing a bit weird
![image-resize](https://cloud.githubusercontent.com/assets/877271/2946353/ef442a8e-d9ea-11e3-9768-409f1083697a.png)

**Comment by tdhartwick** [comment]
Our new v2 templates have addressed this. We're no longer supporting v1 of Ink. We're more than happy to accept a PR on our v1.0.0 branch, but we recommend using our new F4E2 templates.
Thanks!
