### ISSUE TITLE
Fonts not working due to quotation marks in some email clients

### ISSUE THREAD

**Issue by samglover** [zurb/foundation-emails#84]
In some email clients, the quotation marks around "Helvetica" and "Arial" in the following code seem to interfere, resulting in the ugly default font.

```
body, table.body, h1, h2, h3, h4, h5, h6, p, td {
  color: #222222;
  font-family: "Helvetica", "Arial", sans-serif;
  font-weight: normal;
  padding:0;
  margin: 0;
  text-align: left;
  line-height: 1.3;
}
```

Removing the quotation marks seems to do the trick.

**Comment by tdhartwick** [comment]
Looks like this has been addressed! We're still accepting PRs for v1, however we recommend using the most recent F4E2 code.
Thanks!
