### ISSUE TITLE
Only the text within buttons is clickable

### ISSUE THREAD

**Issue by samglover** [zurb/foundation-emails#85]
The CSS for buttons results in a nice, graphical button, but only the text is clickable. The rest of the button is just for looks. Here's one way to fix it:

```
table.button td a,
table.tiny-button td a,
table.small-button td a,
table.medium-button td a,
table.large-button td a {
  display: block;
  height: 100%;
  width: 100%;
}
```
Making the `a` element expand to fill the `td` container results in a fully-clickable button.

**Comment by davidklebanoff** [comment]
Odd, I noticed that the [official documentation](http://zurb.com/ink/docs.php#buttons) has the suggested width and block settings added to the buttons, but the latest version of Ink v1.0.5 doesn't have the changes. So now the official documentation is inconsistent with the release.

**Comment by lancesells** [comment]
Take out the padding from the button css so your button is the height of your text. 
Then in your button href css add: 

```
line-height: 3.6em;
display: inline-block;
width: 100%;
```

**Comment by lime** [comment]
Does anyone have any insight on how compatible this approach is? I've understood that Outlook doesn't deal too well with block-level links.

There are a number of ways that claim to work across clients, (like [buttons.cm](http://buttons.cm) mentioned above, or [this article from Litmus](https://litmus.com/blog/a-guide-to-bulletproof-buttons-in-email-design)), but few of them are responsive. It would be fantastic if we could come up with a variation that could be made part of Ink.

**Comment by niyando** [comment]
@samglover for your solution --> :+1:

**Comment by tdhartwick** [comment]
We've addressed the button issues in v2. We chose to pursue the hybrid approach of padding and borders, making the clickable area much larger. We're no longer supporting v1, however we're more than happy to merge a PR into the v1.0.0 branch!
