### ISSUE TITLE
Column ordering

### ISSUE THREAD

**Issue by webbrum** [zurb/foundation-emails#87]
Hi! Great framework! 

The problem:
When I have a image aligned to the left and content to the right, then when i resize the browser the image get fixed to the top. I need the image to be fixed below the text on mobile view.

Now I have solved it by having two different containers with the same images and content but in opposite align, one for desktop view and one for mobile view.

Is there a better way to solve this today?

**Comment by tdhartwick** [comment]
We've introduced a small and large grid which helps address the problem you're referring to. We recommend using v2, however we're happy to merge in PRs into our v1.0.0 branch. 
Thanks!

**Comment by lalop** [comment]
@tdhartwick sorry but I don't see how this helps addressing this problem ?
`show-for-large` and `hide-for-large` adress this, isn't it ?
