### ISSUE TITLE
Three Column Layout doesn´t expand on Andriod 4.2

### ISSUE THREAD

**Issue by Neffle** [zurb/foundation-emails#88]
Hej there! First of all, thanks for the great work you did here!

I´m having some problems with the three column layout on my LG G2:

![three-cols](https://cloud.githubusercontent.com/assets/5119676/3146044/8eedce0e-ea40-11e3-960c-ed2950212b8f.png)

Any idea what might be wrong? Is it related to the Android EMail Pinch-To-Zoom feature?

Code:

```
<table class="container">
	<tr>
		<td>

			<table class="row">
				<tr>
					<td class="wrapper">

						<table class="four columns">
							<tr>
								<td>
									CONTENT
								</td>
								<td class="expander"></td>
							</tr>
						</table>

					</td>

					<td class="wrapper">

						<table class="four columns">
							<tr>
								<td>
									CONTENT
								</td>
								<td class="expander"></td>
							</tr>
						</table>

					</td>

					<td class="wrapper last">

						<table class="four columns">
							<tr>
								<td>
									CONTENT
								</td>
								<td class="expander"></td>
							</tr>
						</table>

					</td>
				</tr>
			</table>

		</td>
	</tr>
</table>
```

**Comment by tdhartwick** [comment]
We've updated to `th`'s in v2, which should address Android responsive issues. We recommend using v2, however we're more than happy to merge a PR for our v1.0.0 request.
Thanks!
