### ISSUE TITLE
Discussion -  Workflow

### ISSUE THREAD

**Issue by tdhartwick** [zurb/foundation-emails#9]
We've created a brand new Gulp workflow for Foundation for emails including a command line interface to templataize emails, inline them and modify Sass.  We want to know if this is even a thing you're interested in using! We have a few questions around this:

1. Will you use our gulp set up?
2. Does Inky do what you need it to do?
3. Is there anything you're using that you'd love to see?

**Comment by gakimball** [comment]
This issue was moved to zurb/ink#160
