### ISSUE TITLE
Buttons not appearing correctly for iphone mail app

### ISSUE THREAD

**Issue by nneal** [zurb/foundation-emails#90]
```html
<table class="row">
  <tr>
    <td class="wrapper last">
      <table class="six columns">
        <tr>
          <td>
            <table class="medium-button">
              <tr>
                <td>
                  <%= link_to 'Answer this Question', question_url(@question) %>
                </td>
              </tr>
            </table>
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>
```

results in this:

![screen shot 2014-06-06 at 12 08 16 am](https://cloud.githubusercontent.com/assets/1542516/3197465/e53bd5f6-ed49-11e3-94b6-e540451c32a3.png)

ios 7, iphone 5s, default mail app

**Comment by jacksaunders** [comment]
The buttons are a fixed width try reducing your font size with media queries

**Comment by rafibomb** [comment]
The buttons have side padding but if the text is too long it will look like your example.
