### ISSUE TITLE
Yahoo won't centralize email

### ISSUE THREAD

**Issue by eudennis** [zurb/foundation-emails#94]
I made various test and Yahoo won't centralize the email content, even that is working with Outlook (2010, 2007 and outlook.com), Gmail and Apple Mail. There is anything that I need to attend to?

**Comment by tdhartwick** [comment]
We've addressed this in v2. We're no longer supporting v1, but we're more than happy to merge a PR into our v1.0.0 branch. Thanks!

**Comment by ghost** [comment]
@tdhartwick I'm having an issue with Yahoo not centering the button.  I'm using 
`<center><button href="">Shop Now</button></center>`

The weird thing is the button somtimes works in yahoo and sometimes doesn't. I'm at a loss as to what this could be. I've searched and searched on google which is how I came across this.
