### ISSUE TITLE
Ink grid offset usage

### ISSUE THREAD

**Issue by kevpohl** [zurb/foundation-emails#95]
The offset usage is slightly vague in the docs. The offsets only work across email clients if the offset number and the column number adds up to 12. But using offsets in other ways, for example to centre columns or to nudge groups of columns around the page doesn’t work well concistently.

Empty columns are still the best way to offset content: https://www.emailonacid.com/app/acidtest/viewresult/sz9Qwujqw8EBdpgpT33S4oU1MfEy6of5ifUK62QTRobnK

**Comment by csavory** [comment]
I agree with this.  I just ran into this bug.  The following will create a create a centered button that is 180px wide in Chrome, FF and Safari, but fails to do so in IE9.  

```html
<table class="row">
	<tr>
		<td class="wrapper last offset-by-four">

			<table class="four columns">
				<tr>
					<td>

						<table class="button radius">
							<tr>
								<td><a href="/">Text</a></td>
							</tr>
						</table>
						
					</td>
					<td class="expander"></td>
				</tr>
			</table>

		</td>
	</tr>
</table>
```

**Comment by brettdewoody** [comment]
After running a few dozen tests I can also confirm the `offset-by-x` method does not work consistently. Specifically in AOL Chrome (Mac), AOL Chrome (Win), AOL IE 9, Gmail IE 9.

Switching to empty columns provides a much more consistent result.

**Comment by tdhartwick** [comment]
Looks like we've merged a pr related to this for v1. This should be addressed in v2 as well. We're no longer supporting v1, but we're more than happy to merge PR's into our v1.0.0 branch.
