### ISSUE TITLE
margin / padding issue in Gmail & AOL

### ISSUE THREAD

**Issue by mattwschneider** [zurb/foundation-emails#96]
If you use http://zurb.com/ink/inliner.php, we noticed an issue with the inliner that causes rendering issues with Gmail and AOL.  If the left padding or left margin is set to 0px but the top, right, bottom is set to something greater than 0px, it will create margin or padding style attribute with only 3 properties (leaving out the 4th – left property). Examples: ‘padding: 10px 0 10px;’ ‘margin: 10px 0 20px’.  To fix we need to manually go through and set the 4 (left) property to 0. Examples: ‘padding: 10px 0 10px 0;’ ‘margin: 10px 0 20px 0’.

**Comment by tdhartwick** [comment]
We've updated our inliner for v2, which also applies to v1. Let us know if you're still having issues with this! Thanks!
